# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJvqhlZZyjgy493YBPjvWNONq7jwkVqG
"""

import hashlib
from cryptography.fernet import Fernet


# USER DATABASE (hashed)

users = {
    "admin": hashlib.sha256("admin123".encode()).hexdigest(),
    "user": hashlib.sha256("user123".encode()).hexdigest(),
    "Yajat": hashlib.sha256("yajat152".encode()).hexdigest(),
    "Shanvi": hashlib.sha256("shanvi051".encode()).hexdigest()
}

roles = {
    "admin": "admin",
    "user": "user",
    "Yajat": "admin",
    "Shanvi": "admin"
}


#  ENCRYPTION KEY

key = Fernet.generate_key()
cipher = Fernet(key)


#  SAFE INPUT FUNCTION

def safe_input(prompt, default=None):
    try:
        return input(prompt)
    except:
        print(f"Input not supported. Using default: {default}")
        return default


#  LOGIN SYSTEM

def login():
    username = safe_input("Enter username: ", "admin")
    password = safe_input("Enter password: ", "admin123")

    hashed = hashlib.sha256(password.encode()).hexdigest()

    if username in users and users[username] == hashed:
        print("✅ Login Successful!")
        return username
    else:
        print("❌ Invalid Credentials")
        return None


#  ENCRYPT / DECRYPT

def encrypt_message(message):
    return cipher.encrypt(message.encode())

def decrypt_message(encrypted):
    return cipher.decrypt(encrypted).decode()


#  HASHING

def generate_hash(message):
    return hashlib.sha256(message.encode()).hexdigest()


#  COMMAND EXECUTION

def execute_command(user, command):
    role = roles[user]

    if command == "unlock door":
        if role != "admin":
            print("❌ Access Denied: Admin only")
        else:
            print("🔓 Door Unlocked")

    elif command == "lock door":
        print("🔒 Door Locked")

    elif command == "get temperature":
        print(" Temperature is 25°C")

    else:
        print("❌ Invalid Command")


#  SEND COMMAND

def send_command(user):
    command = safe_input("Enter command: ", "get temperature")

    encrypted = encrypt_message(command)
    hash_val = generate_hash(command)

    print("\n Sending encrypted command...")
    receive_command(user, encrypted, hash_val)


#  RECEIVE COMMAND

def receive_command(user, encrypted, received_hash):
    try:
        decrypted = decrypt_message(encrypted)
        new_hash = generate_hash(decrypted)

        print(" Receiving command...")

        if new_hash != received_hash:
            print("❌ Data Tampered!")
            return

        print("✅ Data Verified")
        print("🔓 Decrypted Command:", decrypted)

        execute_command(user, decrypted)

    except:
        print("❌ Decryption Failed")


#  AUTO DEMO MODE

def auto_demo():
    print("\n Running Auto Demo Mode...\n")
    user = "admin"

    commands = ["get temperature", "lock door", "unlock door"]

    for cmd in commands:
        print(f"\n Command: {cmd}")
        encrypted = encrypt_message(cmd)
        hash_val = generate_hash(cmd)
        receive_command(user, encrypted, hash_val)


#  MAIN PROGRAM

def main():
    print(" Secure Smart Home System")

    user = login()
    if not user:
        auto_demo()
        return

    while True:
        print("\nCommands:")
        print("1. Send Command")
        print("2. Auto Demo")
        print("3. Exit")

        choice = safe_input("Enter choice: ", "2")

        if choice == "1":
            send_command(user)
        elif choice == "2":
            auto_demo()
        elif choice == "3":
            print(" Exiting...")
            break
        else:
            print("❌ Invalid choice")

# Run
main()